## “If the only tool you have is a hammer, you tend to see every problem as a nail.”
## *Abraham Maslow*

### Every data science project is unique, that's why it is a best practice to always make your custom code for data cleaning and pre processing, but..

### Sometimes you just wanna compare classification or regression algotitms, make a quick prototipation, test, or even learn a new toll. In this cases you don't want to spend too much time clening and pre processing data, so thas is when it is a good ideia to have an auto preprocessing tool around.

# Example of usage

## [House Prices - Advanced Regression Techniques](https://www.kaggle.com/c/house-prices-advanced-regression-techniques)
### A super popular data science problem avaliable on [kaggle](https://www.kaggle.com/). All most every biginner Data Science student has tryed to solve it.

### In this exaple usage tutorial we are going to compare  how regression algorithm is performing with no actual data cleaning and with de usage of the **maslow-proprocessig-toll**

In [1]:
from package.classes import PreProcessor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
import pandas as pd
train = pd.read_csv("test/train.csv")
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

### It consists in a dataframe with 79 columns representing independent variables, and 1 target variable called **Saleprice** (in this tutorial we call it *target column*). It has many missing values, and categorical.

## Method: remove_na_columns()
### The first problem we are going to deal with is the columns wich was a big proportion os missing data. Assuming this features arent valuable to our analysis we are deleting It.
### In the next lines of code we detemine that all columns with a higer percentage of missing values than 40% should be removed

In [2]:
pre = PreProcessor(train)
pre.remove_na_columns(max_na_proportion=0.4) # Max proportion of missing values 40%

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,147500

### As we can see the method remove_na_columns() droped 4 columns

## Method: replace_na_values()
### Now we want all the remainig columns that contains missing values to have it replced. So we call the method replace_na_values()

In [3]:
pre.replace_na_values()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,147500

### The method replace_na_values() replaces all numeric columns with the median value of that columns, and replaces all categorical columns with the mde values of that column

## Method: encode_categorial()
### Now we use the method encode_categorical() to encode categorical columns

In [4]:
pre.encode_categorical()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,3,3,0,4,...,0,0,0,0,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,3,3,0,2,...,0,0,0,0,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,0,3,0,4,...,0,0,0,0,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,0,3,0,0,...,272,0,0,0,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,0,3,0,2,...,0,0,0,0,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,3,3,0,4,...,0,0,0,0,0,8,2007,8,4,175000
1456,1457,20,3,85.0,13175,1,3,3,0,4,...,0,0,0,0,0,2,2010,8,4,210000
1457,1458,70,3,66.0,9042,1,3,3,0,4,...,0,0,0,0,2500,5,2010,8,4,266500
1458,1459,20,3,68.0,9717,1,3,3,0,4,...,112,0,0,0,0,4,2010,8,4,142125
1459,1460,20,3,75.0,9937,1,3,3,0,4,...,0,0,0,0,0,6,2008,8,4,147500

### Encode_categorical() uses pd.LabelEncoder to encode categorical columns

## Method: normalize()
### To deal with skewness and kurtosis we use the function normalize, normalize method uses np.log or np.sqrt to normalize data reducing skewness and kurosis

In [5]:
pre.normalize()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0.000000,4.094345,3,4.174387,9.041922,1,3,3,0,4,...,0,0,0,0,0,0.693147,7.604894,8,4,12.247694
1,0.693147,2.995732,3,4.382027,9.169518,1,3,3,0,2,...,0,0,0,0,0,1.609438,7.604396,8,4,12.109011
2,1.098612,4.094345,3,4.219508,9.328123,1,0,3,0,4,...,0,0,0,0,0,2.197225,7.604894,8,4,12.317167
3,1.386294,4.248495,3,4.094345,9.164296,1,0,3,0,0,...,272,0,0,0,0,0.693147,7.603898,8,0,11.849398
4,1.609438,4.094345,3,4.430817,9.565214,1,0,3,0,2,...,0,0,0,0,0,2.484907,7.604894,8,4,12.429216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,7.283448,4.094345,3,4.127134,8.976768,1,3,3,0,4,...,0,0,0,0,0,2.079442,7.604396,8,4,12.072541
1456,7.284135,2.995732,3,4.442651,9.486076,1,3,3,0,4,...,0,0,0,0,0,0.693147,7.605890,8,4,12.254863
1457,7.284821,4.248495,3,4.189655,9.109636,1,3,3,0,4,...,0,0,0,0,2500,1.609438,7.605890,8,4,12.493130
1458,7.285507,2.995732,3,4.219508,9.181632,1,3,3,0,4,...,112,0,0,0,0,1.386294,7.605890,8,4,11.864462
1459,7.286192,2.995732,3,4.317488,9.204020,1,3,3,0,4,...,0,0,0,0,0,1.791759,7.604894,8,4,11.901583

## Method feature_selction()
### Last but not less important, the method feature_selection() selects the colunmns that has a minimun absolute correlation with the target column, and drop the restant columns

In [6]:
pre.feature_selection()

,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,Foundation,BsmtQual,TotalBsmtSF,HeatingQC,1stFlrSF,...,FullBath,KitchenQual,TotRmsAbvGrd,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,SalePrice
0,1.945910,7.602401,7.602401,196.0,2,2,2,856,0,6.752270,...,2,2,2.079442,0,1,7.602401,1,2,548,12.247694
1,1.791759,7.588830,7.588830,0.0,3,1,2,1262,0,7.140453,...,2,3,1.791759,1,1,7.588830,1,2,460,12.109011
2,1.945910,7.601402,7.601902,162.0,2,2,2,920,0,6.824374,...,2,2,1.791759,1,1,7.601402,1,2,608,12.317167
3,1.945910,7.557473,7.585789,0.0,3,0,3,756,2,6.867974,...,1,2,1.945910,1,5,7.599902,2,3,642,11.849398
4,2.079442,7.600902,7.600902,350.0,2,2,2,1145,0,7.043160,...,2,2,2.197225,1,1,7.600902,1,3,836,12.429216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1.791759,7.600402,7.600902,0.0,3,2,2,953,0,6.859615,...,2,3,1.945910,1,1,7.600402,1,2,460,12.072541
1456,1.791759,7.589842,7.594884,119.0,3,1,2,1542,4,7.636752,...,2,3,1.945910,2,1,7.589842,2,2,500,12.254863
1457,1.945910,7.570959,7.603898,0.0,0,4,3,1152,0,7.080026,...,2,2,2.197225,2,1,7.570959,1,1,252,12.493130
1458,1.609438,7.575585,7.598900,0.0,3,1,3,1078,2,6.982863,...,1,2,1.609438,0,1,7.575585,2,1,240,11.864462
1459,1.609438,7.583248,7.583248,0.0,2,1,3,1256,2,7.135687,...,1,3,1.791759,0,1,7.583248,0,1,276,11.901583

### As we can see, the melhod feature_selection selected 21 columns that presanted a correletion above 40% with the target column SalePrice.

## Now we have a clean and preprocessed dataframe to start playing with our the ML os NN tools...

In [7]:
pre_processed_data = pre.df
pre_processed_data.head()

,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,Foundation,BsmtQual,TotalBsmtSF,HeatingQC,1stFlrSF,...,FullBath,KitchenQual,TotRmsAbvGrd,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,SalePrice
0,1.945910,7.602401,7.602401,196.0,2,2,2,856,0,6.752270,...,2,2,2.079442,0,1,7.602401,1,2,548,12.247694
1,1.791759,7.588830,7.588830,0.0,3,1,2,1262,0,7.140453,...,2,3,1.791759,1,1,7.588830,1,2,460,12.109011
2,1.945910,7.601402,7.601902,162.0,2,2,2,920,0,6.824374,...,2,2,1.791759,1,1,7.601402,1,2,608,12.317167
3,1.945910,7.557473,7.585789,0.0,3,0,3,756,2,6.867974,...,1,2,1.945910,1,5,7.599902,2,3,642,11.849398
4,2.079442,7.600902,7.600902,350.0,2,2,2,1145,0,7.043160,...,2,2,2.197225,1,1,7.600902,1,3,836,12.429216

## Let's have som fun and use this celan and pre-processed data to make the cross validation os a SVR model

In [8]:
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline
scaler = StandardScaler()
pipe = Pipeline([('std_scaler', StandardScaler()), #Building a pipeline with a StandardScaler and a SVR regressor
                ('SVR', SVR())])


X , y = pre_processed_data.drop(columns=pre_processed_data.columns[-1]), pre_processed_data.iloc[:, -1] #Splitting our data betweeen independent and target variables
scores = cross_validate(pipe, X, y, cv=5, n_jobs=-1)

mean_score_accuracy = scores['test_score'].mean()
print(f"Model's mean accuracy: {round(mean_score_accuracy, 2)}%")

Model's mean accuracy: 0.83%

## And that's all, this pre processor toll makes the job os cleaning and preproeecessing data a little easyer and faster, enjoy!!